#create a fake switch that will turn on the heatzy radiator (comfort) and turn off (eco or away)
switch:
  - platform: template
    switches:
      chauffage_salle_de_bain:
        friendly_name: 'Chauffage Salle de Bain'
        icon_template: mdi:radiator
        value_template: "{{ is_state_attr('climate.salle_de_bain', 'preset_mode', 'comfort') }}"
        turn_on:
          service: climate.set_preset_mode
          data:
            entity_id: climate.salle_de_bain
            preset_mode: 'comfort'
        turn_off:
          service: climate.set_preset_mode
          data:
            entity_id: climate.salle_de_bain
            preset_mode: 'away'
 
 #This custom thermostat use an external sensor (in this case an Oregon sensor), and the switch defined above.
 climate:
  - platform: generic_thermostat
    name: Thermostat Salle de Bain
    heater: switch.chauffage_salle_de_bain
    target_sensor: sensor.oregon_salle_de_bain_temperature
    min_temp: 14
    max_temp: 22
    ac_mode: false
    target_temp: 18
    min_cycle_duration:
      seconds: 60
    away_temp: 14
    hot_tolerance: 0
    cold_tolerance: 0
    precision: 0.1
